### ISSUE TITLE
Critical synchronization bug results into going back in time

### ISSUE THREAD

**Issue by bruno-f-cruz** [harp-tech/protocol#48]
Consider a rig where a FLIR camera is being externally triggered by an harp behavior board using DO0. When looking at the difference between the timestamps of adjacent frames and triggers, I get the following plot:

![image](https://github.com/harp-tech/device.behavior/assets/7049351/901e0295-4570-4141-aa58-5246aee7fc6e)

As you can see, while the camera operates at a steady 8.3ms per frame, two frames in >400k seem to have a lower-than-expected timestamp.

 - Set framerate matches the average frame rate of the camera (120fps)
 - The first frame is emitted AFTER the start trigger and the last before the stop trigger event. 
 - The number of frames and number of triggers match.

The two "faulty" frames look like:

```
Frame 187419 has a timestamp difference of 0.00669 s
                FrameAcquired MessageType     Diff
Time                                              
2992896.986816           True       EVENT 0.008352
2992896.995136           True       EVENT 0.008320
2992897.001824           True       EVENT 0.006688
2992897.010176           True       EVENT 0.008352


Frame 341022 has a timestamp difference of 0.00621 s
                FrameAcquired MessageType     Diff
Time                                              
2994176.990112           True       EVENT 0.008352
2994176.998432           True       EVENT 0.008320
2994177.004640           True       EVENT 0.006208
2994177.012960           True       EVENT 0.008320
```

One import point, is that the bug seems to happen around the second roll-over so I am wondering if this is a problem related with the clock synchronization. It is kinda weird that according to the camera the period remains stable but not according to the behavior board. I suspect this might be because the PWM task is running on the MCU clock and not on the Harp clock. Once the clock synchronizes (and corrects the harp clock) it results in a mis-timestamped trigger as seen by the non-linear harp clock. While this seems like an ok behavior in general if the correction of the harp timestamp is small, it seems weird that such a big gap is found (2ms) between the timestamped reported by the camera and the one reported by harp.

**Comment by bruno-f-cruz** [comment]
More data on this bug

Other sessions produce a rather weird bug where the jump in time is actually closer to 1 full second:
```python
                0      diff
Time                       
2487628.957536  1  0.008352
2487628.965888  1  0.008320
2487628.974208  1  0.008352
2487628.982560  1  0.008320
2487628.990880  1 -0.974720
2487628.016160  1  0.991392
2487629.007552  1  0.008320
2487629.015872  1  0.008352

```

I am not sure if this is the same bug or a mixture of two bugs (the one described above + non atomic update of the two time keeping registers).

**Comment by bruno-f-cruz** [comment]
@filcarv suggested connecting a clock generator and a subordinate board. Measure both synch led outputs. Unplug the synch cable and check how long it takes to drift the heartbeat.

**Comment by glopesdev** [comment]
@bruno-f-cruz @filcarv We also just found this on long-term data collection epochs. We've seen two different asymmetrical patterns, but essentially same features as @bruno-f-cruz described.

It's interesting that this was not present in our earlier datasets. We used to have a rare bug where PWM rise times would update non-atomically but this would manifest as a jump forward in time, followed by a jump backwards in time of the same amount. It's more concerning if we have now gaps which are non-symmetric.

**Comment by Poofjunior** [comment]
Here's the Pico strategy for periodic behavior. 
![harp_sync_drawing_reference](https://github.com/user-attachments/assets/67b66c3b-d654-4cf5-b0bd-935ba85bb341)

Heartbeats are scheduled 1s into the future relative to the current Harp Time whole second. If Harp time is additionally updated within that interval, it is ignored. When the interval has elapsed, a message is issued with the current Harp time, which may be more up-to-date than when the heartbeat event was scheduled.

**Comment by Poofjunior** [comment]
Updated image:
![harp_sync_drawing_reference (2)](https://github.com/user-attachments/assets/eef3c422-d6e6-4d5d-a69f-455c2b411c59)

**Comment by glopesdev** [comment]
A preview version of the atxmega core was released which should fix this:
https://github.com/harp-tech/atxmega/releases/tag/1.14-preview3

Currently waiting on tests before closing.

**Comment by bruno-f-cruz** [comment]
> A preview version of the atxmega core was released which should fix this: https://github.com/harp-tech/atxmega/releases/tag/1.14-preview3
> 
> Currently waiting on tests before closing.

Run a quick test. 24 hours of recording of a TimestampGeneratorGen3 (on the 1.14 preview) connected to two behavior boards: one running on the 1.14 preview and a second running on the latest 1.13. I am optimistic since I still see the bug in the 1.13 fw, but no problem was detected in the new 1.14 release.

![Image](https://github.com/user-attachments/assets/5510c33f-0ed0-4863-99df-e1da346e76be)

![Image](https://github.com/user-attachments/assets/5241ba00-ef02-4c59-bc54-07c511b7bee6)

**Comment by bruno-f-cruz** [comment]
I am closing this as completed.
